
.SUPPORTED_LANGUAGES = c(
  "chinese",
  "danish",
  "dutch",
  "english",
  "french",
  "german",
  "greek",
  "italian",
  "japanese",
  "lithuanian",
  "multi-language",
  "norwegian bokmål",
  "polish",
  "portuguese",
  "romanian",
  "russian",
  "spanish",
  "afrikaans",
  "albanian",
  "arabic",
  "armenian",
  "basque",
  "bengali",
  "bulgarian",
  "catalan",
  "croatian",
  "czech",
  "estonian",
  "finnish",
  "gujarati",
  "hebrew",
  "hindi",
  "hungarian",
  "icelandic",
  "indonesian",
  "irish",
  "kannada",
  "kyrgyz",
  "latvian",
  "ligurian",
  "luxembourgish",
  "macedonian",
  "malayalam",
  "marathi",
  "nepali",
  "persian",
  "sanskrit",
  "serbian",
  "setswana",
  "sinhala",
  "slovak",
  "slovenian",
  "swedish",
  "tagalog",
  "tamil",
  "tatar",
  "telugu",
  "thai",
  "turkish",
  "ukrainian",
  "urdu",
  "vietnamese",
  "yoruba"
)

test_that("ascii code converter", {
  obj = str_to_ascii_code(.SUPPORTED_LANGUAGES)
  expect_equal(ascii_code_to_str(obj), .SUPPORTED_LANGUAGES)
})
